# Generated by Django 5.1.4 on 2024-12-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_alter_salao_cnpj"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "salao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.salao"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servico", models.CharField(max_length=255)),
                ("data_hora", models.DateTimeField()),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
