# Generated by Django 5.1.4 on 2024-12-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0006_alter_salao_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="salao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.salao",
            ),
        ),
    ]
