# Generated by Django 5.1.4 on 2024-12-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salao",
            name="cnpj",
            field=models.CharField(
                default="00000000000000", max_length=14, unique=True
            ),
            preserve_default=False,
        ),
    ]
