# Generated by Django 5.1.4 on 2024-12-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_salao_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salao",
            name="cnpj",
            field=models.CharField(default="00000000000", max_length=14),
        ),
    ]
