# Generated by Django 5.1.4 on 2024-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_salao_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salao",
            name="cnpj",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
